name: Format

on:
  [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format the code
        run: go fmt
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "fix: auto format by github-actions"
